# application: Habit-Tracker-190817
# version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /(nightly|morning_reminder|afternoon_reminder|evening_reminder)
  script: index.py
  login: admin

- url: /.*
  script: index.py
  secure: always

builtins:
- remote_api: on

libraries:
- name: numpy
  version: "1.6.1"
- name: ssl
  version: "latest"
